services:
  microgame-bot:
    build:
      context: .
      target: local
    env_file:
      - .env
    volumes:
      - .:/src/app
    # ports:
    #   - "8000:8080"
    depends_on:
      - postgres
      - nats1
      - nats2
      - nats3
    restart: unless-stopped

  postgres:
    image: postgres:18.1-bookworm
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats1:
    image: nats:2.12.3-alpine
    command: ["-c", "/etc/nats/nats.conf"]
    environment:
      - NATS_SERVER_NAME=nats1
      - NATS_CLUSTER_NAME=nats-cluster
      - NATS_ROUTES=nats://nats1:6222,nats://nats2:6222,nats://nats3:6222
      - NATS_STORE_DIR=/data/jetstream/nats1
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
      - nats-data:/data/jetstream

  nats2:
    image: nats:2.12.3-alpine
    command: ["-c", "/etc/nats/nats.conf"]
    environment:
      - NATS_SERVER_NAME=nats2
      - NATS_CLUSTER_NAME=nats-cluster
      - NATS_ROUTES=nats://nats1:6222,nats://nats2:6222,nats://nats3:6222
      - NATS_STORE_DIR=/data/jetstream/nats2
    ports:
      - "4223:4222"
      - "6223:6222"
      - "8223:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
      - nats-data:/data/jetstream

  nats3:
    image: nats:2.12.3-alpine
    command: ["-c", "/etc/nats/nats.conf"]
    environment:
      - NATS_SERVER_NAME=nats3
      - NATS_CLUSTER_NAME=nats-cluster
      - NATS_ROUTES=nats://nats1:6222,nats://nats2:6222,nats://nats3:6222
      - NATS_STORE_DIR=/data/jetstream/nats3
    ports:
      - "4224:4222"
      - "6224:6222"
      - "8224:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
      - nats-data:/data/jetstream

volumes:
  postgres-data:
    driver: local
  nats-data:
    driver: local
