apiVersion: v1
kind: Secret
metadata:
  name: microgame-bot-env
type: Opaque
stringData:
  LOGS__LEVEL: debug
  LOGS__IS_PRETTY: false
  LOGS__WITH_CONTEXT: true
  LOGS__WITH_SOURCES: true
  APP__MAX_GAME_COUNT: 10
  APP__LOCKER_DRIVER: memory
  APP__LOCKER_TTL: 720h
  POSTGRES__URL: postgres://app:app@postgres:5432/app
  TELEGRAM__TOKEN: 
  TELEGRAM__ADMIN_IDS: 
  TELEGRAM__DEBUG: false
  TELEGRAM__WEBHOOK_URL: https://microgame.example.com
  TELEGRAM__WEBHOOK_PATH: /
  TELEGRAM__WEBHOOK_ADDR: 0.0.0.0:8080
  # UNUSED
  NATS__URL: nats://nats1:4222,nats://nats2:4222,nats://nats3:4222
  NATS__NKEY_SEED: 
  NATS__NKEY_PUBLIC: 
