apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-microgame-bot
spec:
  instances: 1
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  enableSuperuserAccess: false
  postgresql:
    parameters:
      max_connections: "100"
  storage:
    size: 1Gi
    storageClass: local-retain
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
